### PR TITLE
Use provisioner type attribute

### LINKED ISSUE #133: Cachier does not resolve provisioners with Vagrant 1.7.1
Due to a modification in Vagrant 1.7.1 or earlier cachier does not resolve provisioners correctly anymore. Thus for example the chef caching is broken.

The bug applies for example here:
https://github.com/fgrehm/vagrant-cachier/blob/master/lib/vagrant-cachier/cap/linux/chef_file_cache_path.rb

The vagrant-butcher plugin created by @cassianoleal already solved this bug here:
https://github.com/cassianoleal/vagrant-butcher/commit/81cc73c02f17af272a870bce02ff287190768a51

### PR DESCRIPTION
**Pull request by Yserz**
Vagrant changed the provisioner name attribute to type in version 1.7.1.

fixes #133

### CODE REVIEW

**Comment by jkulak** [comment]
Would be great to see that merged!

**Comment by fgrehm** [comment]
Thanks and sorry it took so long! The 1.2.0 version of the plugin will come out with this in a few ;-)

File: lib/vagrant-cachier/cap/linux/chef_file_cache_path.rb [hunk 1]
```diff
@@ -6,7 +6,7 @@ module ChefFileCachePath
           def self.chef_provisioner?(machine)
             provisioners = machine.config.vm.provisioners
             chef_provisioners = [:chef_solo, :chef_client]
-            compat_provisioners = provisioners.keep_if { |p| chef_provisioners.include? p.name }
+            compat_provisioners = provisioners.keep_if { |p| chef_provisioners.include? p.name || p.type }
```
Comment (tknerr) [inline lib/vagrant-cachier/cap/linux/chef_file_cache_path.rb]: @fgrehm @Yserz that might be a bit too optimistic and works only if the provisioner name is not set. However, note that you can have named provisioners in which case the `p.name` might be anything:
https://docs.vagrantup.com/v2/provisioning/basic_usage.html

Here's how I solved it in one of my vagrant plugins:
https://github.com/tknerr/vagrant-toplevel-cookbooks/commit/ae188ee09f572d91efd88c0c071cbd83c44d416d

Or @sethvargo here:
https://github.com/berkshelf/vagrant-berkshelf/blob/cd5ee78f28ee9f6bec1b72fcdbcb042b0155aa04/lib/vagrant-berkshelf/helpers.rb#L69-L86

/cc @cassianoleal
